import "../styles/globals.css";
import type { AppProps } from "next/app";
import { ThemeProvider } from "styled-components";
import theme from "../styles/theme";
import Head from "next/dist/next-server/lib/head";
import { createGlobalStyle } from "styled-components";
import { ApolloProvider } from "@apollo/client";
import ApolloClientInstance from "../logic/database";

const GlobalStyle = createGlobalStyle`
  body {
    font-size: ${(props) => props.theme.fonts.size.medium}px;
  }
`;

function MyApp({ Component, pageProps }: AppProps) {
  return (
    <ApolloProvider client={ApolloClientInstance}>
      <ThemeProvider theme={theme}>
        <GlobalStyle />
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <meta
            name="viewport"
            content="width=device-width, initial-scale=1.0"
          ></meta>
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Component {...pageProps} />
      </ThemeProvider>
    </ApolloProvider>
  );
}
export default MyApp;
